# Generated by Django 6.0.4 on 2026-04-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaPago',
            fields=[
                ('id_frecuencia_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('dias', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'FrecuenciaPago',
            },
        ),
        migrations.CreateModel(
            name='Metodo_de_pago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'MetodoDePago',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Referencia',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('monto_de_prestamo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('n_cuotas', models.IntegerField()),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_limite', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliente')),
                ('frecuencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.frecuenciapago')),
            ],
            options={
                'db_table': 'Credito',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_cuota', models.IntegerField()),
                ('fecha_esperada', models.DateField()),
                ('fecha_pago_real', models.DateTimeField(blank=True, null=True)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_intereses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.credito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.estado')),
            ],
            options={
                'db_table': 'Cuota',
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_cuota', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.credito')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cuota')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.metodo_de_pago')),
            ],
            options={
                'db_table': 'Abono',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.referencia'),
        ),
    ]
