# Generated by Django 6.0.4 on 2026-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='monto_total',
            new_name='montoTotal',
        ),
    ]
