# Generated by Django 6.0.4 on 2026-04-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_rename_monto_total_abono_montototal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='montoTotal',
            new_name='monto_total',
        ),
    ]
