# Generated by Django 6.0.4 on 2026-04-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_rename_montototal_abono_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Zona',
            },
        ),
        migrations.AddField(
            model_name='credito',
            name='porcentaje_seguro',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.zona'),
        ),
    ]
